# Generated by ClusterForge from apps manifest. Safe to edit.

module "api" {
  source = "../../../../modules/workloads/ecs/service"

  name               = "api"
  environment        = "dev"
  cluster_arn        = module.ecs_cluster.cluster_arn
  subnet_ids         = module.network.private_subnet_ids
  security_group_ids = var.app_security_group_ids

  image          = "ghcr.io/company/api:1.0.0"
  desired_count  = 2
  container_port = 8080
  protocol       = "tcp"
  environment_variables = {
    "NODE_ENV" = "production"
  }
  # Secret values are not generated.
  # Replace value_from with existing SSM Parameter Store or Secrets Manager ARNs,
  # and ensure the task execution role can read them.
  # secrets = [
  #   {
  #     name       = "DATABASE_URL"
  #     value_from = "replace-with-ssm-or-secrets-manager-arn"
  #   },
  # ]
  autoscaling = {
    enabled          = true
    min_capacity     = 2
    max_capacity     = 5
    cpu_target_value = 70
  }
}

variable "app_security_group_ids" {
  description = "Security group IDs for rendered ECS application services."
  type        = list(string)
}
