# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force.

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Project     = "demo"
      Environment = "dev"
      ManagedBy   = "ClusterForge"
    }
  }
}
