# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force.

variable "region" {
  description = "AWS region for this environment."
  type        = string
  default     = "eu-central-1"
}

variable "project" {
  description = "Project name used for tags."
  type        = string
  default     = "demo"
}

variable "environment" {
  description = "Environment name."
  type        = string
  default     = "dev"
}

variable "name" {
  description = "Name prefix and ECS cluster name."
  type        = string
  default     = "clusterforge-dev-ecs"
}

variable "owner" {
  description = "Optional owner tag value."
  type        = string
  default     = ""
}

variable "cost_center" {
  description = "Optional cost center tag value."
  type        = string
  default     = ""
}

variable "extra_tags" {
  description = "Additional AWS tags."
  type        = map(string)
  default     = {}
}

variable "vpc_cidr_block" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.30.0.0/16"
}

variable "availability_zones" {
  description = "Availability zones for the network."
  type        = list(string)
  default     = ["eu-central-1a", "eu-central-1b"]
}

variable "public_subnet_cidrs" {
  description = "Public subnet CIDR blocks matching availability_zones order."
  type        = list(string)
  default     = ["10.30.0.0/20", "10.30.16.0/20"]
}

variable "private_subnet_cidrs" {
  description = "Private subnet CIDR blocks matching availability_zones order."
  type        = list(string)
  default     = ["10.30.128.0/20", "10.30.144.0/20"]
}

variable "enable_nat_gateway" {
  description = "Whether to create NAT gateway resources."
  type        = bool
  default     = true
}

variable "single_nat_gateway" {
  description = "Whether to create one shared NAT gateway instead of one per availability zone."
  type        = bool
  default     = true
}

variable "enable_container_insights" {
  description = "Whether to enable ECS Container Insights."
  type        = bool
  default     = true
}

variable "capacity_providers" {
  description = "ECS capacity providers attached to the cluster."
  type        = list(string)
  default     = ["FARGATE", "FARGATE_SPOT"]
}
