# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force.

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0, < 7.0"
    }
  }
}
