# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force.

terraform {
  backend "s3" {
    bucket         = "clusterforge-test-state"
    key            = "clusterforge/dev/terraform.tfstate"
    region         = "eu-central-1"
    dynamodb_table = "clusterforge-test-locks"
    encrypt        = true
  }
}

