package app

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"github.com/alekpopovic/clusterforge/cli/internal/bindings"
	"github.com/alekpopovic/clusterforge/cli/internal/config"
)

const renderHeader = "# Generated by ClusterForge from apps manifest. Safe to edit."

type RenderOptions struct {
	RootDir string
}

type renderData struct {
	Header          string
	ModuleName      string
	App             Manifest
	EnvName         string
	Environment     config.Environment
	ModulesPath     string
	PrimaryPort     int
	PortName        string
	BindingEnv      map[string]string
	BindingComments []string
}

func Render(rootDir, envName string, env config.Environment, manifest Manifest) (string, error) {
	manifest.ApplyDefaults()
	if err := manifest.Validate(); err != nil {
		return "", err
	}
	if !IsSupportedOrchestrator(env.Orchestrator) {
		return "", fmt.Errorf("unsupported orchestrator %q for app rendering; supported targets are Kubernetes variants and ecs", env.Orchestrator)
	}
	if manifest.CloudIdentity.Enabled && env.Orchestrator != "eks" && env.Orchestrator != "ecs" {
		return "", fmt.Errorf("cloud identity provider %q is not supported for orchestrator %q; the MVP supports EKS IRSA and ECS task roles", manifest.CloudIdentity.Provider, env.Orchestrator)
	}
	outDir := filepath.Join(env.Path, "apps")
	if env.EffectiveLayout() == "stacked" {
		stackPath, err := env.StackPath("apps")
		if err != nil {
			return "", err
		}
		outDir = stackPath
	}
	modulesPath, err := relativeModulesPath(rootDir, outDir)
	if err != nil {
		return "", err
	}
	registry, err := bindings.Load(env.Path)
	if err != nil {
		return "", err
	}
	resolvedBindings, err := bindings.Resolve(registry, manifest.Dependencies)
	if err != nil {
		return "", err
	}
	data := renderData{
		Header:          renderHeader,
		ModuleName:      sanitizeModuleName(manifest.Name),
		App:             manifest,
		EnvName:         envName,
		Environment:     env,
		ModulesPath:     modulesPath,
		PrimaryPort:     primaryPort(manifest),
		PortName:        primaryPortName(manifest),
		BindingEnv:      resolvedBindings.Environment,
		BindingComments: resolvedBindings.Comments,
	}

	tpl, err := template.New("app").Funcs(template.FuncMap{
		"quote":      strconv.Quote,
		"lower":      strings.ToLower,
		"hclMap":     hclMap,
		"hclList":    hclList,
		"hclExprMap": hclExpressionMap,
		"hclPorts":   hclPorts,
		"hclSecrets": hclSecrets,
		"hclRes":     hclResources,
	}).Parse(templateFor(env.Orchestrator))
	if err != nil {
		return "", fmt.Errorf("parse app render template: %w", err)
	}
	var rendered bytes.Buffer
	if err := tpl.Execute(&rendered, data); err != nil {
		return "", fmt.Errorf("render app %s: %w", manifest.Name, err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", fmt.Errorf("create app render directory %s: %w", outDir, err)
	}
	outPath := filepath.Join(outDir, manifest.Name+".tf")
	if err := os.WriteFile(outPath, rendered.Bytes(), 0o644); err != nil {
		return "", fmt.Errorf("write rendered app %s: %w", outPath, err)
	}
	return outPath, nil
}

func templateFor(orchestrator string) string {
	switch orchestrator {
	case "eks", "kubernetes", "k3s", "rke2", "gke", "aks":
		return kubernetesTemplate
	case "ecs":
		return ecsTemplate
	default:
		return ""
	}
}

func IsSupportedOrchestrator(orchestrator string) bool {
	switch orchestrator {
	case "eks", "kubernetes", "k3s", "rke2", "gke", "aks", "ecs":
		return true
	default:
		return false
	}
}

const kubernetesTemplate = `{{ .Header }}
{{- range .BindingComments }}
# {{ . }}
{{- end }}

{{- if .App.CloudIdentity.Enabled }}
module "{{ .ModuleName }}_irsa" {
  source = "{{ .ModulesPath }}/cloud/aws/irsa-role"

  name                 = {{ quote (printf "%s-%s" .App.Name .EnvName) }}
  environment          = {{ quote .EnvName }}
  oidc_provider_arn    = module.eks.oidc_provider_arn
  oidc_provider_url    = module.eks.oidc_provider_url
  namespace            = {{ quote .EnvName }}
  service_account_name = {{ quote .App.Name }}
  policy_arns          = {{ hclList .App.CloudIdentity.PolicyARNs 2 }}
  inline_policies      = {{ hclMap .App.CloudIdentity.InlinePolicies 2 }}
}

{{- end }}

module "{{ .ModuleName }}" {
  source = "{{ .ModulesPath }}/workloads/kubernetes/app"

  name      = {{ quote .App.Name }}
  namespace = {{ quote .EnvName }}
  image     = {{ quote .App.Image }}
  replicas  = {{ .App.Replicas }}

{{- if .App.CloudIdentity.Enabled }}
  service_account = {
    create = true
    name   = {{ quote .App.Name }}
    annotations = {
      "eks.amazonaws.com/role-arn" = module.{{ .ModuleName }}_irsa.role_arn
    }
  }
{{- end }}

{{- if .App.Ports }}
  ports = {{ hclPorts .App.Ports 2 }}

{{- end }}
{{- if .BindingEnv }}
  env = merge(
    {{ hclMap .App.Env 4 }},
    {{ hclExprMap .BindingEnv 4 }}
  )

{{- else if .App.Env }}
  env = {{ hclMap .App.Env 2 }}

{{- end }}
{{- if .App.SecretEnv }}
  # Secret values are not generated. These references expect existing Kubernetes Secrets.
  secret_env = {{ hclSecrets .App.SecretEnv 2 }}

{{- end }}
{{- if .App.Resources }}
  resources = {{ hclRes .App.Resources 2 }}

{{- end }}
  ingress = {
    enabled = {{ .App.Ingress.Enabled }}
{{- if .App.Ingress.Enabled }}
    host    = {{ quote .App.Ingress.Host }}
    path    = {{ quote .App.Ingress.Path }}
    tls     = {{ .App.Ingress.TLS }}
{{- end }}
  }

  autoscaling = {
{{- if .App.Autoscaling.Enabled }}
    enabled      = true
    min_replicas = {{ .App.Autoscaling.MinReplicas }}
    max_replicas = {{ .App.Autoscaling.MaxReplicas }}
    cpu_percent  = {{ .App.Autoscaling.CPUPercent }}
{{- else }}
    enabled = false
{{- end }}
  }
}
`

const ecsTemplate = `{{ .Header }}
{{- range .BindingComments }}
# {{ . }}
{{- end }}

module "{{ .ModuleName }}" {
  source = "{{ .ModulesPath }}/workloads/ecs/service"

  name               = {{ quote .App.Name }}
  environment        = {{ quote .EnvName }}
  cluster_arn        = module.ecs_cluster.cluster_arn
  subnet_ids         = module.network.private_subnet_ids
  security_group_ids = var.app_security_group_ids

  image          = {{ quote .App.Image }}
  desired_count  = {{ .App.Replicas }}
  container_port = {{ .PrimaryPort }}
  protocol       = {{ quote (lower .PortName) }}

{{- if .App.CloudIdentity.Enabled }}
{{- if .App.CloudIdentity.TaskRoleARN }}
  task_role_arn = {{ quote .App.CloudIdentity.TaskRoleARN }}
{{- else }}
  task_role_policy_arns    = {{ hclList .App.CloudIdentity.PolicyARNs 2 }}
  task_role_inline_policies = {{ hclMap .App.CloudIdentity.InlinePolicies 2 }}
{{- end }}
{{- end }}

{{- if .BindingEnv }}
  environment_variables = merge(
    {{ hclMap .App.Env 4 }},
    {{ hclExprMap .BindingEnv 4 }}
  )

{{- else if .App.Env }}
  environment_variables = {{ hclMap .App.Env 2 }}

{{- end }}
{{- if .App.SecretEnv }}
  # Secret values are not generated.
  # Replace value_from with existing SSM Parameter Store or Secrets Manager ARNs,
  # and ensure the task execution role can read them.
  # secrets = [
{{- range $name, $_ := .App.SecretEnv }}
  #   {
  #     name       = {{ quote $name }}
  #     value_from = "replace-with-ssm-or-secrets-manager-arn"
  #   },
{{- end }}
  # ]

{{- end }}
  autoscaling = {
{{- if .App.Autoscaling.Enabled }}
    enabled          = true
    min_capacity     = {{ .App.Autoscaling.MinReplicas }}
    max_capacity     = {{ .App.Autoscaling.MaxReplicas }}
    cpu_target_value = {{ .App.Autoscaling.CPUPercent }}
{{- else }}
    enabled = false
{{- end }}
  }
}

variable "app_security_group_ids" {
  description = "Security group IDs for rendered ECS application services."
  type        = list(string)
}
`

func relativeModulesPath(rootDir, fromDir string) (string, error) {
	absRoot, err := filepath.Abs(rootDir)
	if err != nil {
		return "", fmt.Errorf("resolve root dir: %w", err)
	}
	absFrom, err := filepath.Abs(fromDir)
	if err != nil {
		return "", fmt.Errorf("resolve output dir: %w", err)
	}
	rel, err := filepath.Rel(absFrom, filepath.Join(absRoot, "modules"))
	if err != nil {
		return "", fmt.Errorf("calculate relative module path: %w", err)
	}
	return filepath.ToSlash(rel), nil
}

func sanitizeModuleName(name string) string {
	var out strings.Builder
	for _, r := range name {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			out.WriteRune(r)
			continue
		}
		out.WriteRune('_')
	}
	return out.String()
}

func primaryPort(manifest Manifest) int {
	if len(manifest.Ports) == 0 {
		return 80
	}
	return manifest.Ports[0].ContainerPort
}

func primaryPortName(manifest Manifest) string {
	if len(manifest.Ports) == 0 || manifest.Ports[0].Protocol == "" {
		return "tcp"
	}
	return manifest.Ports[0].Protocol
}

func hclMap(values map[string]string, indent int) string {
	if len(values) == 0 {
		return "{}"
	}
	pad := strings.Repeat(" ", indent)
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var out strings.Builder
	out.WriteString("{\n")
	for _, key := range keys {
		out.WriteString(fmt.Sprintf("%s  %s = %s\n", pad, strconv.Quote(key), strconv.Quote(values[key])))
	}
	out.WriteString(pad + "}")
	return out.String()
}

func hclList(values []string, indent int) string {
	if len(values) == 0 {
		return "[]"
	}
	pad := strings.Repeat(" ", indent)
	var out strings.Builder
	out.WriteString("[\n")
	for _, value := range values {
		out.WriteString(fmt.Sprintf("%s  %s,\n", pad, strconv.Quote(value)))
	}
	out.WriteString(pad + "]")
	return out.String()
}

func hclExpressionMap(values map[string]string, indent int) string {
	if len(values) == 0 {
		return "{}"
	}
	pad := strings.Repeat(" ", indent)
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var out strings.Builder
	out.WriteString("{\n")
	for _, key := range keys {
		out.WriteString(fmt.Sprintf("%s  %s = %s\n", pad, strconv.Quote(key), values[key]))
	}
	out.WriteString(pad + "}")
	return out.String()
}

func hclPorts(ports []Port, indent int) string {
	if len(ports) == 0 {
		return "[]"
	}
	pad := strings.Repeat(" ", indent)
	var out strings.Builder
	out.WriteString("[\n")
	for _, port := range ports {
		out.WriteString(pad + "  {\n")
		out.WriteString(fmt.Sprintf("%s    name           = %s\n", pad, strconv.Quote(port.Name)))
		out.WriteString(fmt.Sprintf("%s    container_port = %d\n", pad, port.ContainerPort))
		out.WriteString(fmt.Sprintf("%s    protocol       = %s\n", pad, strconv.Quote(port.Protocol)))
		out.WriteString(pad + "  },\n")
	}
	out.WriteString(pad + "]")
	return out.String()
}

func hclSecrets(secrets map[string]SecretRef, indent int) string {
	if len(secrets) == 0 {
		return "{}"
	}
	pad := strings.Repeat(" ", indent)
	keys := make([]string, 0, len(secrets))
	for key := range secrets {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var out strings.Builder
	out.WriteString("{\n")
	for _, key := range keys {
		ref := secrets[key]
		out.WriteString(fmt.Sprintf("%s  %s = {\n", pad, strconv.Quote(key)))
		out.WriteString(fmt.Sprintf("%s    secret_name = %s\n", pad, strconv.Quote(ref.SecretName)))
		out.WriteString(fmt.Sprintf("%s    secret_key  = %s\n", pad, strconv.Quote(ref.SecretKey)))
		out.WriteString(pad + "  }\n")
	}
	out.WriteString(pad + "}")
	return out.String()
}

func hclResources(resources Resources, indent int) string {
	pad := strings.Repeat(" ", indent)
	var out strings.Builder
	out.WriteString("{\n")
	if resources.CPURequest != "" {
		out.WriteString(fmt.Sprintf("%s  cpu_request    = %s\n", pad, strconv.Quote(resources.CPURequest)))
	}
	if resources.MemoryRequest != "" {
		out.WriteString(fmt.Sprintf("%s  memory_request = %s\n", pad, strconv.Quote(resources.MemoryRequest)))
	}
	if resources.CPULimit != "" {
		out.WriteString(fmt.Sprintf("%s  cpu_limit      = %s\n", pad, strconv.Quote(resources.CPULimit)))
	}
	if resources.MemoryLimit != "" {
		out.WriteString(fmt.Sprintf("%s  memory_limit   = %s\n", pad, strconv.Quote(resources.MemoryLimit)))
	}
	out.WriteString(pad + "}")
	return out.String()
}
