# Generated by ClusterForge from apps manifest. Safe to edit.

module "api" {
  source = "../../../../modules/workloads/kubernetes/app"

  name      = "api"
  namespace = "dev"
  image     = "ghcr.io/company/api:1.0.0"
  replicas  = 2
  ports = [
    {
      name           = "http"
      container_port = 8080
      protocol       = "TCP"
    },
  ]
  env = {
    "NODE_ENV" = "production"
  }
  # Secret values are not generated. These references expect existing Kubernetes Secrets.
  secret_env = {
    "DATABASE_URL" = {
      secret_name = "api-secrets"
      secret_key  = "database-url"
    }
  }
  resources = {
    cpu_request    = "100m"
    memory_request = "128Mi"
    cpu_limit      = "500m"
    memory_limit   = "512Mi"
  }
  ingress = {
    enabled = true
    host    = "api.dev.example.com"
    path    = "/"
    tls     = true
  }

  autoscaling = {
    enabled      = true
    min_replicas = 2
    max_replicas = 5
    cpu_percent  = 70
  }
}
