# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force.

variable "region" {
  description = "AWS region for this environment."
  type        = string
  default     = "eu-central-1"
}

variable "project" {
  description = "Project name used for tags."
  type        = string
  default     = "demo"
}

variable "environment" {
  description = "Environment name."
  type        = string
  default     = "dev"
}

variable "name" {
  description = "Name prefix and EKS cluster name."
  type        = string
  default     = "clusterforge-dev-eks"
}

variable "owner" {
  description = "Optional owner tag value."
  type        = string
  default     = ""
}

variable "cost_center" {
  description = "Optional cost center tag value."
  type        = string
  default     = ""
}

variable "extra_tags" {
  description = "Additional AWS tags."
  type        = map(string)
  default     = {}
}

variable "vpc_cidr_block" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.20.0.0/16"
}

variable "availability_zones" {
  description = "Availability zones for the network."
  type        = list(string)
  default     = ["eu-central-1a", "eu-central-1b"]
}

variable "public_subnet_cidrs" {
  description = "Public subnet CIDR blocks matching availability_zones order."
  type        = list(string)
  default     = ["10.20.0.0/20", "10.20.16.0/20"]
}

variable "private_subnet_cidrs" {
  description = "Private subnet CIDR blocks matching availability_zones order."
  type        = list(string)
  default     = ["10.20.128.0/20", "10.20.144.0/20"]
}

variable "enable_nat_gateway" {
  description = "Whether to create NAT gateway resources."
  type        = bool
  default     = true
}

variable "single_nat_gateway" {
  description = "Whether to create one shared NAT gateway instead of one per availability zone."
  type        = bool
  default     = true
}

variable "public_subnet_tags" {
  description = "Additional tags for public subnets."
  type        = map(string)
  default     = {}
}

variable "private_subnet_tags" {
  description = "Additional tags for private subnets."
  type        = map(string)
  default     = {}
}

variable "kubernetes_version" {
  description = "EKS Kubernetes version."
  type        = string
  default     = "1.30"
}

variable "endpoint_public_access" {
  description = "Whether the EKS API endpoint is publicly reachable."
  type        = bool
  default     = true
}

variable "endpoint_private_access" {
  description = "Whether the EKS API endpoint is reachable from inside the VPC."
  type        = bool
  default     = true
}

variable "public_access_cidrs" {
  description = "CIDR blocks allowed to reach the public EKS API endpoint."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "enabled_cluster_log_types" {
  description = "EKS control plane log types to enable."
  type        = list(string)
  default     = ["api", "audit", "authenticator"]
}

variable "enable_vpc_cni_addon" {
  description = "Whether to manage the Amazon VPC CNI EKS add-on."
  type        = bool
  default     = true
}

variable "enable_coredns_addon" {
  description = "Whether to manage the CoreDNS EKS add-on."
  type        = bool
  default     = true
}

variable "enable_kube_proxy_addon" {
  description = "Whether to manage the kube-proxy EKS add-on."
  type        = bool
  default     = true
}

variable "enable_ebs_csi_driver_addon" {
  description = "Whether to manage the AWS EBS CSI Driver EKS add-on."
  type        = bool
  default     = false
}

variable "default_node_instance_types" {
  description = "Instance types for the default managed node group."
  type        = list(string)
  default     = ["t3.medium"]
}

variable "default_node_capacity_type" {
  description = "Capacity type for the default managed node group."
  type        = string
  default     = "ON_DEMAND"
}

variable "default_node_min_size" {
  description = "Minimum size for the default managed node group."
  type        = number
  default     = 1
}

variable "default_node_desired_size" {
  description = "Desired size for the default managed node group."
  type        = number
  default     = 2
}

variable "default_node_max_size" {
  description = "Maximum size for the default managed node group."
  type        = number
  default     = 4
}

variable "default_node_disk_size" {
  description = "Disk size in GiB for the default managed node group."
  type        = number
  default     = 50
}
