# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force.

# Existing Kubernetes environment. This root does not create a cluster,
# network, or cloud resources. Render apps into this environment with:
#   cf app render <name> --env dev

# Optional platform bootstrap. Enable only after reviewing the target cluster.
#
# module "platform_bootstrap" {
#   source = "../../../modules/platform/kubernetes/bootstrap"
#
#   enable_ingress_nginx    = false
#   enable_cert_manager     = false
#   enable_metrics_server   = true
#   enable_external_dns     = false
#   enable_prometheus_stack = false
#   enable_loki             = false
#   enable_argocd           = false
# }
