# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force.

output "kubeconfig_context" {
  description = "Configured kubeconfig context."
  value       = var.kubeconfig_context
}
