# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force.

variable "kubeconfig_path" {
  description = "Path to the kubeconfig for the existing cluster."
  type        = string
  default     = "~/.kube/config"
}

variable "kubeconfig_context" {
  description = "Kubeconfig context for the existing cluster."
  type        = string
  default     = ""
}

variable "environment" {
  description = "ClusterForge environment name."
  type        = string
  default     = "dev"
}
