package generator

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/alekpopovic/clusterforge/cli/internal/config"
	templateassets "github.com/alekpopovic/clusterforge/cli/templates"
)

const header = "# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force."

// ModuleRef is injected with the release tag for distributed CLI binaries.
var ModuleRef = "main"

var environmentFiles = []string{
	"versions.tf",
	"backend.tf",
	"providers.tf",
	"main.tf",
	"variables.tf",
	"outputs.tf",
	"terraform.tfvars.example",
	"README.md",
}

type Options struct {
	Force        bool
	DryRun       bool
	Cloud        string
	Orchestrator string
	Layout       string
	Backend      config.Backend
	Project      string
	RootDir      string
	TemplatesDir string
	Stdout       io.Writer
	AWSAccount   config.AWSAccount
}

type Result struct {
	Target  string
	Actions []Action
}

type Action struct {
	Path   string
	Exists bool
}

type templateData struct {
	Header       string
	Environment  string
	Cloud        string
	Region       string
	Orchestrator string
	Project      string
	Name         string
	ModulesPath  string
	ModulesRef   string
	BackendBlock string
	Stack        string
	StateComment string
	AWSProfile   string
	AWSRoleARN   string
}

func Generate(name string, env config.Environment, opts Options) (*Result, error) {
	if env.Path == "" {
		return nil, fmt.Errorf("environment %q has no path", name)
	}
	if opts.Cloud != "" {
		env.Cloud = opts.Cloud
	}
	if opts.Orchestrator != "" {
		env.Orchestrator = opts.Orchestrator
	}
	if opts.Layout != "" {
		env.Layout = opts.Layout
	}
	if env.Layout == "" {
		env.Layout = "simple"
	}
	target := fmt.Sprintf("%s-%s", env.Cloud, env.Orchestrator)
	if !supportedTarget(target) {
		return nil, fmt.Errorf("unsupported generate target %q; supported targets are aws-eks, aws-ecs, azure-aks, gcp-gke, local-k3s, local-rke2, and existing-kubernetes", target)
	}
	if env.Layout != "simple" && env.Layout != "stacked" {
		return nil, fmt.Errorf("unsupported layout %q; expected simple or stacked", env.Layout)
	}
	backend := opts.Backend
	if backend.Type == "" {
		backend.Type = "local"
	}
	if err := backend.Validate(name); err != nil {
		return nil, err
	}
	if isProd(name) && backend.EffectiveType() == "local" {
		fmt.Fprintf(defaultWriter(opts.Stdout), "warning: prod environment %q is configured with local backend\n", name)
	}

	rootDir := opts.RootDir
	if rootDir == "" {
		rootDir = "."
	}
	templatesDir := opts.TemplatesDir

	if env.Layout == "stacked" {
		return generateStacked(name, env, opts, rootDir, backend)
	}

	modulesPath, modulesRef, err := moduleSource(rootDir, env.Path)
	if err != nil {
		return nil, err
	}
	data := templateData{
		Header:       header,
		Environment:  name,
		Cloud:        env.Cloud,
		Region:       env.Region,
		Orchestrator: env.Orchestrator,
		Project:      defaultString(opts.Project, "clusterforge"),
		Name:         fmt.Sprintf("clusterforge-%s-%s", name, env.Orchestrator),
		ModulesPath:  modulesPath,
		ModulesRef:   modulesRef,
		BackendBlock: renderBackendBlock(name, "", backend),
		AWSProfile:   opts.AWSAccount.Profile,
		AWSRoleARN:   opts.AWSAccount.RoleARN,
	}

	result := &Result{Target: target}
	actions := make([]Action, 0, len(environmentFiles))
	for _, file := range environmentFiles {
		path := filepath.Join(env.Path, file)
		_, statErr := os.Stat(path)
		exists := statErr == nil
		if exists && !opts.Force && !opts.DryRun {
			return nil, fmt.Errorf("%s already exists; use --force to overwrite it", path)
		}
		if statErr != nil && !os.IsNotExist(statErr) {
			return nil, fmt.Errorf("stat %s: %w", path, statErr)
		}
		actions = append(actions, Action{Path: path, Exists: exists})
	}
	result.Actions = actions

	if opts.DryRun {
		printDryRun(opts.Stdout, result.Actions)
		return result, nil
	}
	if err := os.MkdirAll(env.Path, 0o755); err != nil {
		return nil, fmt.Errorf("create environment path %s: %w", env.Path, err)
	}
	for _, action := range result.Actions {
		rendered, err := renderFile(templatesDir, target, filepath.Base(action.Path), data)
		if err != nil {
			return nil, err
		}
		if err := os.WriteFile(action.Path, rendered, 0o644); err != nil {
			return nil, fmt.Errorf("write %s: %w", action.Path, err)
		}
	}
	return result, nil
}

func supportedTarget(target string) bool {
	switch target {
	case "aws-eks", "aws-ecs", "azure-aks", "gcp-gke", "local-k3s", "local-rke2", "existing-kubernetes", "existing-nomad":
		return true
	default:
		return false
	}
}

func generateStacked(name string, env config.Environment, opts Options, rootDir string, backend config.Backend) (*Result, error) {
	result := &Result{Target: fmt.Sprintf("%s-%s-stacked", env.Cloud, env.Orchestrator)}
	stacks := env.Stacks
	if stacks == nil {
		stacks = config.Stacks{}
	}
	for _, stackName := range config.StackOrder() {
		stack := stacks[stackName]
		if stack.Path == "" {
			stack.Path = filepath.Join(env.Path, stackName)
		}
		modulesPath, modulesRef, err := moduleSource(rootDir, stack.Path)
		if err != nil {
			return nil, err
		}
		data := templateData{
			Header:       header,
			Environment:  name,
			Cloud:        env.Cloud,
			Region:       env.Region,
			Orchestrator: env.Orchestrator,
			Project:      defaultString(opts.Project, "clusterforge"),
			Name:         fmt.Sprintf("clusterforge-%s-%s", name, env.Orchestrator),
			ModulesPath:  modulesPath,
			ModulesRef:   modulesRef,
			BackendBlock: renderBackendBlock(name, stackName, backend),
			Stack:        stackName,
			StateComment: remoteStateComment(stackName),
		}
		for _, file := range environmentFiles {
			path := filepath.Join(stack.Path, file)
			_, statErr := os.Stat(path)
			exists := statErr == nil
			if exists && !opts.Force && !opts.DryRun {
				return nil, fmt.Errorf("%s already exists; use --force to overwrite it", path)
			}
			if statErr != nil && !os.IsNotExist(statErr) {
				return nil, fmt.Errorf("stat %s: %w", path, statErr)
			}
			result.Actions = append(result.Actions, Action{Path: path, Exists: exists})
			if opts.DryRun {
				continue
			}
			rendered := renderStackFile(file, data)
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				return nil, fmt.Errorf("create stack path %s: %w", filepath.Dir(path), err)
			}
			if err := os.WriteFile(path, []byte(rendered), 0o644); err != nil {
				return nil, fmt.Errorf("write %s: %w", path, err)
			}
		}
	}
	if opts.DryRun {
		printDryRun(opts.Stdout, result.Actions)
	}
	return result, nil
}

func renderStackFile(file string, data templateData) string {
	switch file {
	case "versions.tf":
		return fmt.Sprintf("%s\n\nterraform {\n  required_version = \">= 1.6.0\"\n}\n", data.Header)
	case "backend.tf":
		return data.BackendBlock
	case "providers.tf":
		return fmt.Sprintf("%s\n\n# Configure providers for the %s stack here.\n", data.Header, data.Stack)
	case "variables.tf":
		return fmt.Sprintf("%s\n\nvariable \"region\" {\n  description = \"Cloud region for this stack.\"\n  type        = string\n  default     = %q\n}\n", data.Header, data.Region)
	case "outputs.tf":
		return fmt.Sprintf("%s\n\n# Export only values that downstream stacks need.\n", data.Header)
	case "terraform.tfvars.example":
		return fmt.Sprintf("region = %q\n", data.Region)
	case "README.md":
		return fmt.Sprintf("# %s %s stack\n\n%s\n\nStack order: `network`, `cluster`, `platform`, `apps`.\n\nUse `terraform_remote_state` or another explicit output handoff between stacks. For local examples, local backend remote state can be used carefully; production should use a remote backend with locking.\n", data.Environment, data.Stack, data.StateComment)
	case "main.tf":
		return fmt.Sprintf("%s\n\n# %s stack for %s (%s/%s).\n%s\n\n# TODO: compose focused ClusterForge modules for this stack.\n# modules path from here: %s\n", data.Header, title(data.Stack), data.Environment, data.Cloud, data.Orchestrator, data.StateComment, data.ModulesPath)
	default:
		return data.Header + "\n"
	}
}

func remoteStateComment(stack string) string {
	switch stack {
	case "network":
		return "This stack owns foundational networking outputs such as VPC and subnet IDs."
	case "cluster":
		return "Read network outputs from the network stack before creating the orchestrator."
	case "platform":
		return "Read cluster connection outputs from the cluster stack before installing platform add-ons."
	case "apps":
		return "Read platform or cluster outputs before rendering workload modules."
	default:
		return "Use explicit stack outputs for cross-stack dependencies."
	}
}

func renderBackendBlock(environment, stack string, backend config.Backend) string {
	switch backend.EffectiveType() {
	case "s3":
		lines := []string{
			header,
			"",
			"terraform {",
			"  backend \"s3\" {",
			fmt.Sprintf("    bucket         = %q", backend.Bucket),
			fmt.Sprintf("    key            = %q", backendKey(environment, stack, backend.KeyPrefix)),
			fmt.Sprintf("    region         = %q", backend.Region),
		}
		if backend.DynamoDBTable != "" {
			lines = append(lines, fmt.Sprintf("    dynamodb_table = %q", backend.DynamoDBTable))
		}
		lines = append(lines,
			"    encrypt        = true",
			"  }",
			"}",
			"",
		)
		return strings.Join(lines, "\n")
	case "azurerm":
		return fmt.Sprintf("%s\n\n# TODO: configure azurerm backend settings before use.\nterraform {\n  backend \"azurerm\" {}\n}\n", header)
	case "gcs":
		return fmt.Sprintf("%s\n\n# TODO: configure gcs backend settings before use.\nterraform {\n  backend \"gcs\" {}\n}\n", header)
	default:
		return fmt.Sprintf("%s\n\nterraform {\n  backend \"local\" {}\n}\n", header)
	}
}

func backendKey(environment, stack, prefix string) string {
	if prefix == "" {
		prefix = path.Join("clusterforge", environment)
	}
	if stack == "" {
		return path.Join(prefix, "terraform.tfstate")
	}
	return path.Join(prefix, stack, "terraform.tfstate")
}

func renderFile(templatesDir, target, file string, data templateData) ([]byte, error) {
	templatePath := path.Join("env", target, file+".tmpl")
	var (
		content []byte
		err     error
	)
	if templatesDir == "" {
		content, err = templateassets.FS.ReadFile(templatePath)
	} else {
		templatePath = filepath.Join(templatesDir, filepath.FromSlash(templatePath))
		content, err = os.ReadFile(templatePath)
	}
	if err != nil {
		return nil, fmt.Errorf("read template %s: %w", templatePath, err)
	}
	tpl, err := template.New(file).Parse(string(content))
	if err != nil {
		return nil, fmt.Errorf("parse template %s: %w", templatePath, err)
	}
	var rendered bytes.Buffer
	if err := tpl.Execute(&rendered, data); err != nil {
		return nil, fmt.Errorf("render template %s: %w", templatePath, err)
	}
	return rendered.Bytes(), nil
}

func relativeModulesPath(rootDir, envPath string) (string, error) {
	absRoot, err := filepath.Abs(rootDir)
	if err != nil {
		return "", fmt.Errorf("resolve root dir: %w", err)
	}
	absEnv, err := filepath.Abs(envPath)
	if err != nil {
		return "", fmt.Errorf("resolve environment path: %w", err)
	}
	rel, err := filepath.Rel(absEnv, filepath.Join(absRoot, "modules"))
	if err != nil {
		return "", fmt.Errorf("calculate relative module path: %w", err)
	}
	return filepath.ToSlash(rel), nil
}

func moduleSource(rootDir, envPath string) (string, string, error) {
	modulesDir := filepath.Join(rootDir, "modules")
	if info, err := os.Stat(modulesDir); err == nil && info.IsDir() {
		modulesPath, err := relativeModulesPath(rootDir, envPath)
		return modulesPath, "", err
	} else if err != nil && !os.IsNotExist(err) {
		return "", "", fmt.Errorf("stat modules directory: %w", err)
	}
	return "git::https://github.com/alekpopovic/clusterforge.git//modules", "?ref=" + ModuleRef, nil
}

func printDryRun(out io.Writer, actions []Action) {
	out = defaultWriter(out)
	sorted := append([]Action{}, actions...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Path < sorted[j].Path
	})
	for _, action := range sorted {
		verb := "create"
		if action.Exists {
			verb = "update"
		}
		fmt.Fprintf(out, "%s %s\n", verb, action.Path)
	}
}

func defaultWriter(out io.Writer) io.Writer {
	if out == nil {
		return os.Stdout
	}
	return out
}

func defaultString(value, fallback string) string {
	if value == "" {
		return fallback
	}
	return value
}

func title(value string) string {
	if value == "" {
		return ""
	}
	return strings.ToUpper(value[:1]) + value[1:]
}

func isProd(environment string) bool {
	env := strings.ToLower(environment)
	return env == "prod" || env == "production"
}
