package generator

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"text/template"

	"github.com/textracta/clusterforge/cli/internal/config"
)

const header = "# Generated by ClusterForge. Safe to edit, but regeneration may overwrite with --force."

var environmentFiles = []string{
	"versions.tf",
	"backend.tf",
	"providers.tf",
	"main.tf",
	"variables.tf",
	"outputs.tf",
	"terraform.tfvars.example",
	"README.md",
}

type Options struct {
	Force        bool
	DryRun       bool
	Cloud        string
	Orchestrator string
	Project      string
	RootDir      string
	TemplatesDir string
	Stdout       io.Writer
}

type Result struct {
	Target  string
	Actions []Action
}

type Action struct {
	Path   string
	Exists bool
}

type templateData struct {
	Header       string
	Environment  string
	Cloud        string
	Region       string
	Orchestrator string
	Project      string
	Name         string
	ModulesPath  string
}

func Generate(name string, env config.Environment, opts Options) (*Result, error) {
	if env.Path == "" {
		return nil, fmt.Errorf("environment %q has no path", name)
	}
	if opts.Cloud != "" {
		env.Cloud = opts.Cloud
	}
	if opts.Orchestrator != "" {
		env.Orchestrator = opts.Orchestrator
	}
	target := fmt.Sprintf("%s-%s", env.Cloud, env.Orchestrator)
	if target != "aws-eks" && target != "aws-ecs" {
		return nil, fmt.Errorf("unsupported generate target %q; supported targets are aws-eks and aws-ecs", target)
	}

	rootDir := opts.RootDir
	if rootDir == "" {
		rootDir = "."
	}
	templatesDir := opts.TemplatesDir
	if templatesDir == "" {
		var err error
		templatesDir, err = defaultTemplatesDir()
		if err != nil {
			return nil, err
		}
	}

	modulesPath, err := relativeModulesPath(rootDir, env.Path)
	if err != nil {
		return nil, err
	}
	data := templateData{
		Header:       header,
		Environment:  name,
		Cloud:        env.Cloud,
		Region:       env.Region,
		Orchestrator: env.Orchestrator,
		Project:      defaultString(opts.Project, "clusterforge"),
		Name:         fmt.Sprintf("clusterforge-%s-%s", name, env.Orchestrator),
		ModulesPath:  modulesPath,
	}

	targetDir := filepath.Join(templatesDir, "env", target)
	result := &Result{Target: target}
	actions := make([]Action, 0, len(environmentFiles))
	for _, file := range environmentFiles {
		path := filepath.Join(env.Path, file)
		_, statErr := os.Stat(path)
		exists := statErr == nil
		if exists && !opts.Force && !opts.DryRun {
			return nil, fmt.Errorf("%s already exists; use --force to overwrite it", path)
		}
		if statErr != nil && !os.IsNotExist(statErr) {
			return nil, fmt.Errorf("stat %s: %w", path, statErr)
		}
		actions = append(actions, Action{Path: path, Exists: exists})
	}
	result.Actions = actions

	if opts.DryRun {
		printDryRun(opts.Stdout, result.Actions)
		return result, nil
	}
	if err := os.MkdirAll(env.Path, 0o755); err != nil {
		return nil, fmt.Errorf("create environment path %s: %w", env.Path, err)
	}
	for _, action := range result.Actions {
		rendered, err := renderFile(targetDir, filepath.Base(action.Path), data)
		if err != nil {
			return nil, err
		}
		if err := os.WriteFile(action.Path, rendered, 0o644); err != nil {
			return nil, fmt.Errorf("write %s: %w", action.Path, err)
		}
	}
	return result, nil
}

func renderFile(templateDir, file string, data templateData) ([]byte, error) {
	templatePath := filepath.Join(templateDir, file+".tmpl")
	content, err := os.ReadFile(templatePath)
	if err != nil {
		return nil, fmt.Errorf("read template %s: %w", templatePath, err)
	}
	tpl, err := template.New(file).Parse(string(content))
	if err != nil {
		return nil, fmt.Errorf("parse template %s: %w", templatePath, err)
	}
	var rendered bytes.Buffer
	if err := tpl.Execute(&rendered, data); err != nil {
		return nil, fmt.Errorf("render template %s: %w", templatePath, err)
	}
	return rendered.Bytes(), nil
}

func relativeModulesPath(rootDir, envPath string) (string, error) {
	absRoot, err := filepath.Abs(rootDir)
	if err != nil {
		return "", fmt.Errorf("resolve root dir: %w", err)
	}
	absEnv, err := filepath.Abs(envPath)
	if err != nil {
		return "", fmt.Errorf("resolve environment path: %w", err)
	}
	rel, err := filepath.Rel(absEnv, filepath.Join(absRoot, "modules"))
	if err != nil {
		return "", fmt.Errorf("calculate relative module path: %w", err)
	}
	return filepath.ToSlash(rel), nil
}

func defaultTemplatesDir() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("locate generator source path")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..", "templates")), nil
}

func printDryRun(out io.Writer, actions []Action) {
	if out == nil {
		out = os.Stdout
	}
	sorted := append([]Action{}, actions...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Path < sorted[j].Path
	})
	for _, action := range sorted {
		verb := "create"
		if action.Exists {
			verb = "update"
		}
		fmt.Fprintf(out, "%s %s\n", verb, action.Path)
	}
}

func defaultString(value, fallback string) string {
	if value == "" {
		return fallback
	}
	return value
}
